# Basic Configuration
baseURL = "http://ch-solutions.github.io/"
languageCode = "en-us"
title = "CHS"
theme = "hugo-saasify-theme"

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

# Required Markup Configuration
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true       # Allow HTML in markdown
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Theme Parameters
[params]
  description = "Your site description"
  author = "Your Name"
  logo = "/images/icon.png"      # Path to your logo
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  googleAnalytics = "G-XXXXXXXXXX"  # Only enabled in production
  faviconICO = "/favicon_io/favicon.ico"
  favicon_32 = "/favicon_io/favicon-32x32.png"
  favicon_16 = "/favicon_io/favicon-16x16.png"

  # Header Configuration
  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Header Logo
    [params.header.logo]
      src = "/images/icon.png" 
    
    # Header Buttons (optional)
    [params.header.buttons]
      [params.header.buttons.signIn]
        text = "Sign in"
        url = "/"
      [params.header.buttons.getStarted]
        text = "Sign Up"
        url = "/"

  # Global CTA Configuration (optional)
  [params.cta]
    enable = true
    title = "Ready to Get Started?"
    description = "Join companies using our platform"
    [params.cta.primary_button]
      text = "Get Started"
      url = "/pricing"
    [params.cta.secondary_button]
      text = "View Courses"
      url = "/courses"

  # Social Media Links (optional)
  [params.social]
    linkedin = "/"
    twitter = "/"
    github = "https://github.com/ch-solutions/ch-solutions.github.io"

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Courses"
    url = "/courses"
    weight = 2
  [[menu.main]]
    name = "Company"
    weight = 3
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Privacy", url = "/privacy" },
        { name = "Pricing", url = "/pricing" }
      ]